services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expanders360
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP (used by app)
      - "8025:8025"   # Web UI (view captured emails)

volumes:
  mysql_data:
  mongo_data:
